- aspnet-core/Diagram/Getting-Started.md
- aspnet-core/Grid/Data-Binding.md
- aspnet-core/ReportViewer/Report-DataSources.md
Hi @ChristoIssac,
Worked on Bing report issues, merge these changes.
Regards,
Gowthaman
> SEO-1973_Site_Audit_Issues

- aspnet-core/DataManager/AdvancedFunctionalities.md
- aspnet-core/DataManager/Query.md
- aspnet-core/DataManager/corsdatafetching.md
- aspnet-core/Gantt/Resource-Allocation-View.md
- aspnet-core/Tile/Overview.md
Hi @ChristoIssac,
Worked on Site Audit Bing report issues, merge these changes.
Regards,
Gowthaman
> SEO-2050_Site_Audit_Issues

- aspnet-core-toc.html
> IN-18121-UG-Documentation-aspnetcore

- aspnet-core/Chart/Annotations.md
- aspnet-core/FileExplorer/Behavior-Settings.md
- aspnet-core/FileExplorer/Multiple-Selection.md
- aspnet-core/Grid/Row.md
- aspnet-core/ListBox/Multiple-Selection.md
- aspnet-core/Spreadsheet/Print.md
Worked on site audit issues, merge these changes.
Regards,
Gowthaman
> SEO-2344_Site_Audit_Issues

- aspnet-core-toc.html
- aspnet-core/installation/mac-installer/how-to-install.md
> IN-18200-UG-Documentation-aspnet-core-hotfix

- aspnet-core/Combobox/data-binding.md
- aspnet-core/Combobox/localization.md
- aspnet-core/DataManager/Data-Binding.md
- aspnet-core/TreeView/Template-Option.md
Worked on site audit issues, so merge these changes,
Regards,
Gowthaman
> SEO-2423_Site_Audit_Issues

- aspnet-core/DataManager/Summary.md
- aspnet-core/TreeView/Multiple-Selection.md
Worked on site audit issues, so merge these changes,
Regards,
Gowthaman
> SEO-2475_Site_Audit_Issues

- aspnet-core/DropDownList/DataBinding.md
- aspnet-core/ListBox/Tooltip-Support.md
Hi @ChristoIssac,
|Task Category| Pages With Redirect - Search console|
|:--|:--|
|Issue count| Help site links - 1000 |
|Fixed Count| Help site links - 2 |
|Analysis| Inspecting the links and found referring pages |
|Solution| replaced the exact URL instead of old URL |
|Hotfix PR| https://github.com/syncfusion-content/asp.net-core-docs/pull/236 | 
|Task link|https://syncfusion.atlassian.net/browse/SEO-2684|
|Excel| N/A |
Regards,
Gowthaman
> SEO-2684-Coverage-report-pages-with-redirect

- aspnet-core/DateTimePicker/Localization.md
|Title|Description|
|:--|:--|
|**Task Category** | Need to rename 1 image alt text|
|**Content task link/ Mail screenshot** | N/A |
|**Hotfix PR link** | https://github.com/syncfusion-content/asp.net-core-docs/pull/233
|**Ticket link/Task link** |https://syncfusion.atlassian.net/browse/SEO-2732 |
|**Excel/SharePoint link** | N/A |
> SEO-2732 ASP.NET Core Image Alt Text

- aspnet-core/Grid/Columns.md
|Title|Description|
|:--|:--|
|**Task Category** | Need to rename 18 image alt text|
|**Content task link/ Mail screenshot** | N/A |
|**Hotfix PR link** | https://github.com/syncfusion-content/asp.net-core-docs/pull/232
|**Ticket link/Task link** |https://syncfusion.atlassian.net/browse/SEO-2750 |
|**Excel/SharePoint link** | N/A |
> SEO-2750 - ASP.NET Core Grid images alt text

- aspnet-core/Overview.md
Hi @Aishwarya-Ganesan ,
Please review the changes for Windows Forms HTTP to HTTPS.
Regards,
Yvone.
> SEO-2706 ASP.NET Core HTTP To HTTPS

- aspnet-core/Chart/Axis.md
- aspnet-core/Gantt/Customizations.md
- aspnet-core/GettingStarted/Getting-Started-Linux-2-0-0.md
- aspnet-core/Grid/Sorting.md
Hi @ChristoIssac ,
Please review image alt text changes for ASP.NET Core Controls.
Regards,
Sharly A.
> SEO-2971 - ASP.NET Core Controls image alt text

- aspnet-core/Diagram/Connector.md
- aspnet-core/Grid/Hierarchy-Grid.md
Hi Aishwarya,
Worked on page with redirect for help links, so merge these changes
Regards,
Gowthaman
> SEO-3146-coverage-page-with-redirect-help

- aspnet-core/PdfViewer/Getting-Started.md
Hi @Aishwarya-Ganesan 
Added missing H1 tags.
Regards,
Beryl
> SEO-3151-Core-Missing-H1

- aspnet-core/Chart/Legend.md
- aspnet-core/DataManager/Overview.md
- aspnet-core/Grid/Filtering.md
- aspnet-core/Grid/Overview.md
- aspnet-core/ReportViewer/Limitations.md
- aspnet-core/ReportViewer/Report-Controller.md
- aspnet-core/ReportViewer/SSRS-Configuration.md
Worked on bing report issues, so merge these changes
Regards,
Gowthaman
> SEO-3261-bing-report-issues

- aspnet-core/Overview.md
Please review changes for ASP.NET Core overview.
Regards,
Sharly A.
> SEO-3226 - ASP.NET Core overview

- aspnet-core/SunburstChart/Legend.md
- aspnet-core/SunburstChart/Tooltip.md
Worked on SEMrush report issues, so merge these changes
Regards,
Gowthaman
> SEO-3439-semrush-report-issues

- aspnet-core/DataManager/Filtering.md
- aspnet-core/DatePicker/Getting-Started.md
Hi @Aishwarya-Ganesan ,
Have changed title, description, and h1.
Regards,
Yvone.
> SEO-171762 ASP.NET Core Bing report

- aspnet-core/Accordion/Keyboard-Navigation.md
- aspnet-core/Autocomplete/Data-Binding.md
- aspnet-core/Autocomplete/How-To.md
- aspnet-core/Autocomplete/Keyboard-Interaction.md
- aspnet-core/Autocomplete/Validation.md
- aspnet-core/CheckBox/Easy-customization.md
- aspnet-core/CurrencyTextBox/Keyboard-Interaction.md
- aspnet-core/DataManager/Data-Binding.md
- aspnet-core/DatePicker/Behavior-Settings.md
- aspnet-core/DatePicker/Customization.md
- aspnet-core/DatePicker/Display-Format.md
- aspnet-core/DatePicker/Globalization.md
- aspnet-core/DatePicker/How-To.md
- aspnet-core/DatePicker/Miscellaneous.md
- aspnet-core/DatePicker/State-Persistence.md
- aspnet-core/DateRangePicker/globalization.md
- aspnet-core/DateTimePicker/Localization.md
- aspnet-core/DropDownList/Accessibility.md
- aspnet-core/DropDownList/Customization.md
- aspnet-core/DropDownList/DataBinding.md
- aspnet-core/DropDownList/Functionalities.md
- aspnet-core/FileExplorer/Behavior-Settings.md
- aspnet-core/FileExplorer/Context-Menu.md
- aspnet-core/FileExplorer/Customization.md
- aspnet-core/FileExplorer/Localization.md
- aspnet-core/FileExplorer/Resizing.md
- aspnet-core/FileExplorer/Toolbar.md
Hi @Girija-Rajendran,
Worked on redirection-related fixes, so merge these changes,
Regards,
Gowthaman
> SEO-172685-asp-net-core-redirection-tool-fixes

- aspnet-core/Accordion/Appearance-and-Styling.md
- aspnet-core/Accordion/State-Persistence.md
- aspnet-core/Autocomplete/MultiSelection-modes.md
- aspnet-core/DateTimePicker/Date-Range.md
- aspnet-core/EJTagHelpers.md
- aspnet-core/Menu/Context-Menu.md
- aspnet-core/NumericTextBox/Overview.md
- aspnet-core/PivotGrid/Getting-Started.md
Hi @MallikaRK ,
I have made changes in the description section, please review.
Regards,
Scholar.
> SEO-173277 ASP.NET Core Description too long too short

- aspnet-core-toc.html
> 847601 - Add XlsIO in EJ1 Core UG - HF

- aspnet-core/RadialMenu/TemplateSupport.md
Hello,
I have worked on the missing H1
Regards,
Beryl.
> SEO-176113-Core-Missing-H1

- aspnet-core/DatePicker/Overview.md
Hi @MallikaRK ,
Worked on description too long.
Regards,
SHarly A.
> SEO-180850-ASP.NET-Core-Overview

- aspnet-core/Overview.md
Hi @Yvone-Atieno,
|Title|Description|
|--|--|
|Category|duplicate h1 and title |
|Hotfix PR|https://github.com/syncfusion-content/asp.net-core-docs/pull/410|
|Task||
|Content Ticket||
|UX Ticket||
|Changes made|Reason for changes|
|--|--|
|Added # tag|To remove duplicate h1 in the page |
|Changed meta elements|For proper meta alignments in the page |
Regards,
Edith.
> SEO-187452-Core-duplicate-h1-title
